[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    plerup/EspSoftwareSerial@^8.2.0
build_flags =
    -DBRIDGE_PORT=8023
    -DLINK_BAUD=9600
    -DLINK_RX_PIN=14   ; D5
    -DLINK_TX_PIN=12   ; D6
